### PR TITLE
Updates the README.md instructions

### PR DESCRIPTION
**Pull request by bitoiu**
Hey all,

Just want to say that I found request bin this week for the first time, and I was sad the whole week. This would have saved me years of my life by avoiding a series of networking hacks.

I wanted to try and contribute with a few ideas but while I was going through the instructions to set it up, I noticed the file structure changed a bit.

I've tested these changes and they worked. 

Feel free to close the pull request if the documentation is not up to your standard.

:octocat: :heart:

### CODE REVIEW

**Comment by dthtvwls** [comment]
Hum, I was checking to see if my PR was ever going to get merged and saw you made one to do almost the same. There's actually no need to muck about with app constants, the code already handles it appropriately, provided that the following environment variables exist:

REDIS_URL = (a valid redis url)
REALM = "prod"

The project looks pretty effectively abandoned though, which is a shame.

**Comment by bitoiu** [comment]
I just saw your PR, they differ a tiny bit, I'll still leave this open for now.

> The project looks pretty effectively abandoned though, which is a shame.

:+1: totally!

**Comment by johnsheehan** [comment]
It's not abandoned, we actually make pretty frequent updates to the live site to fix things. The problem is that after we took it over we diverged from this copy of the code and haven't yet found the time to back the changes back in. One of the reasons we've been less responsive to pull requests is to avoid making that more complicated in the future.

**Comment by dthtvwls** [comment]
Forking the code and not merging changes upstream doesn't make this not abandoned, that's worse almost.

**Comment by johnsheehan** [comment]
Our priority is the live site, but that shouldn't stop us from merging in small changes for getting the current code in GitHub up and running. Merging this. We can discuss the other stuff somewhere else.

**Comment by bitoiu** [comment]
thanks @johnsheehan, I was thinking of adding a "copy to clipboard" button next to the response payload. I'll keep checking back for the best time to work on that.

In the meantime, thanks for such an useful app!

**Pull request merged**
