### PR TITLE
Allow any URL after bin ID.

### PR DESCRIPTION
**Pull request by cmouse**
This lets you post in with binid/path, binid.suffix/path, binid.suffix or binid. Same idea as #26 , but taken further. Tested.

### CODE REVIEW

**Comment by johnsheehan** [comment]
What's the use case?

**Comment by cmouse** [comment]
We have code in our application which takes a base url and appends to that. We can't use this to capture the requests without this patch. Application behaviour is not changeable to support requestbin expectations and this makes it lot easier to capture RESTful requests too.

**Comment by johnsheehan** [comment]
Are you self-hosting RequestBin? The public version at requestb.in has
diverged from this repo.



On September 13, 2016 at 11:31:19 AM, Aki Tuomi (notifications@github.com)
wrote:

We have code in our application which takes a base url and appends to that.
We can't use this to capture the requests without this patch. Application
behaviour is not changeable to support requestbin expectations and this
makes it lot easier to capture RESTful requests too.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Runscope/requestbin/pull/27#issuecomment-246741495>,
or mute
the thread

**Comment by cmouse** [comment]
Yes. We are.

**Pull request merged**
